"""Explicacoes das questoes - brasil.

O conteudo esta em ROT13 de proposito: visivel no arquivo, mas
ilegivel a olho nu, para nao entregar a resposta a quem so rola o
arquivo. A funcao explicar() do exercicio decodifica e imprime.

NAO edite este arquivo a mao - ele eh gerado por
NAO_MANDAR_montar_explicacao_brasil.py.
"""

EXPLICACOES = {
    'cidade_da_mirtes': "D - pvqnqr_qn_zvegrf\n\n    raqrerpb_qn_zvegrf['ybpnyvqnqr']   ->  'Erpvsr'\n\nHz pbypurgr fb: rfgr qvpvbanevb ru CYNAB, anb grz qvpvbanevb qrageb qr\nqvpvbanevb. Gbqnf nf vasbeznpbrf rfgnb ab zrfzb aviry.\n\nN crtnqvaun ndhv ru b ABZR qn punir. N pvqnqr anb rfgn rz 'pvqnqr' arz rz\n'zhavpvcvb' - rfgn rz 'ybpnyvqnqr'. Dhrz rfpbyurh bf abzrf sbv dhrz srm n\nNCV, r n tragr yr qb wrvgb dhr irvb. Dhnaqb rfgvire rz qhivqn, cevagr\n`raqrerpb_qn_zvegrf.xrlf()` r byur n yvfgn qr abzrf qvfcbavirvf.\n",
    'uf_da_mirtes': "D - hs_qn_zvegrf\n\n    raqrerpb_qn_zvegrf['hs']   ->  'CR'\n\nPhvqnqb pbz n punir ivmvaun: 'rfgnqb' qribyir 'Creanzohpb', b abzr cbe\nrkgrafb. N crethagn crqr n FVTYN, dhr ru b 'hs'.\n\nNf qhnf vasbeznpbrf irz an zrfzn erfcbfgn - n NCV znaqn nf qhnf sbeznf\ncbedhr arz gbqb zhaqb dhre n zrfzn.\n",
    'bairro_da_mirtes': 'D - onveeb_qn_zvegrf\n\n    raqrerpb_qn_zvegrf[\'onveeb\']   ->  \'Erpvsr\'\n\nFvz, rfgn pregb: b onveeb fr punzn Erpvsr, vthny n pvqnqr. Ru b onveeb\nznvf nagvtb qn pvqnqr - b Erpvsr Nagvtb, baqr svpn b Pnvf qb Ncbyb. Anb\nru reeb frh arz reeb qn NCV.\n\nVffb pbfghzn qne hz fhfgvaub qr "pbcvrv n yvaun reenqn". Pbasven byunaqb\nb qvpvbanevb: \'onveeb\' r \'ybpnyvqnqr\' ernyzragr grz b zrfzb inybe arffr\nraqrerpb. Rz dhnfr gbqb bhgeb PRC ryrf fnb qvsreragrf - b qb Pvpreb, cbe\nrkrzcyb, ru onveeb \'Obn Ivntrz\' r pvqnqr \'Oryb Ubevmbagr\'.\n',
    'quantas_chaves_no_cep': "D - dhnagnf_punirf_ab_prc\n\n    yra(raqrerpb_qn_zvegrf.xrlf())   ->  13\n\nNf germr: 'prc', 'ybtenqbheb', 'pbzcyrzragb', 'havqnqr', 'onveeb',\n'ybpnyvqnqr', 'hs', 'rfgnqb', 'ertvnb', 'votr', 'tvn', 'qqq' r 'fvnsv'.\n\nReeb pbzhz: pbagne fb nf dhr grz pbagrhqb. Gerf qrynf ivrenz inmvnf\n('pbzcyrzragb', 'havqnqr', 'tvn') - znf inmvb anb ru nhfragr. N punir\nrfgn yn, pbz hzn fgevat inmvn qrageb, r b yra pbagn ryn vthny nf bhgenf.\nRffn qvsrerapn ru rkngnzragr b nffhagb qn shapnb grz_pbzcyrzragb, znvf\ncen seragr.\n",
    'ddd_da_mirtes': "D - qqq_qn_zvegrf\n\n    raqrerpb_qn_zvegrf['qqq']   ->  '81'\n\nPbz nfcnf. Ercner dhr GBQB inybe qrfgr qvpvbanevb ru fgevat - vapyhfvir\nbf dhr cnerprz ahzreb ('qqq', 'votr', 'fvnsv'). Sbv qrpvfnb qr dhrz srm n\nNCV, r snm nythz fragvqb: hz QQQ ahapn inv fre fbznqb arz zhygvcyvpnqb, r\ngrz pbqvtb dhr pbzrpn pbz mreb (b '05' svpnevn 5 fr ivenffr ahzreb).\n\nFr ibpr erfcbaqrh 81 frz nfcnf, b unfu ercebin - r n qvsrerapn vzcbegn:\n'81' + 1 qn reeb, radhnagb 81 + 1 qn 82.\n\nFr ibpê byune ab qrohttre, qá cen ire nf nfcnf (bh crqve b glcr qn inevniry)\n",
    'colchetes_ate_a_cidade': "D - pbypurgrf_ngr_n_pvqnqr: dhnagbf pbypurgrf ngr n pvqnqr?\n\n  - hz: raqrerpb_qn_zvegrf['ybpnyvqnqr']  PBEERGB. Rfgr qvpvbanevb ru cynab -\n    hz aviry fb. Gbqb inybe qryr ru hzn fgevat; arauhz ru bhgeb\n    qvpvbanevb.\n  - qbvf: raqrerpb_qn_zvegrf['raqrerpb']['ybpnyvqnqr']  REENQB. Anb rkvfgr\n    punir 'raqrerpb' ndhv. Qbvf pbypurgrf frevnz arprffnevbf fr nythz\n    inybe sbffr bhgeb qvpvbanevb - grz NCV dhr qribyir qvpvbanevb qrageb\n    qr qvpvbanevb, znf b IvnPRC anb ru hzn qrynf.\n  - gerf  REENQB, cryb zrfzb zbgvib, pbz hz aviry vzntvanevb n znvf.\n  - arauhz - n pvqnqr anb irz  REENQB. Irz fvz, an punir 'ybpnyvqnqr'.\n\nInyr thneqne: b qvpvbanevb qb PRC ru b znvf fvzcyrf dhr hzn NCV ragertn -\nghqb ab zrfzb aviry.\n",
    'tipo_do_ddd': "D - gvcb_qb_qqq: b dhr rfgn thneqnqb rz raqrerpb_qn_zvegrf['qqq']?\n\n  - n fgevat '81'  PBEERGB. Byur nf nfcnf ab qvpvbanevb: '81'. Arfgn NCV\n    gbqb inybe ru grkgb, vapyhfvir bf dhr cnerprz ahzreb.\n  - b ahzreb 81  REENQB, r ru b reeb dhr rfgbhen qrcbvf: fr ibpr gragne\n    snmre pbagn pbz vffb ('81' + 1), b Clguba erpynzn dhr anb qn cen\n    fbzne grkgb pbz ahzreb. Fr hz qvn cerpvfne qb ahzreb, pbairegn pbz\n    vag(...).\n  - b ahzreb 81.0  REENQB. Anb un sybng arauhz arffn erfcbfgn.\n  - hzn yvfgn pbz b 8 r b 1  REENQB. Frevn ['8', '1'], pbz pbypurgrf - r\n    anb ru b dhr rfgn yn.\n",
    'chave_que_nao_veio': 'D - punir_dhr_anb_irvb: r `raqrerpb_qn_zvegrf[\'ahzreb\']`?\n\n  - yrinagn XrlReebe r b cebtenzn cnen  PBEERGB. Crqve hzn punir dhr anb\n    rkvfgr ru hz reeb, r reeb rz Clguba vagreebzcr b cebtenzn. N zrafntrz\n    irz pbz b abzr qn punir: XrlReebe: \'ahzreb\'.\n  - qribyir Abar  REENQB, r ru n pbashfnb znvf pbzhz: dhrz qribyir Abar\n    rz irm qr dhroene ru b zrgbqb `.trg`\n    (raqrerpb_qn_zvegrf.trg(\'ahzreb\') -> Abar). B pbypurgr anb creqbn.\n  - qribyir hzn fgevat inmvn, pbzb npbagrpr pbz \'tvn\'  REENQB, r rffn\n    nygreangvin zvfghen qhnf pbvfnf qr cebcbfvgb. B \'tvn\' qribyir fgevat\n    inmvn cbedhr n punir RKVFGR r b inybe qryn ru \'\'. B \'ahzreb\' anb\n    rkvfgr - r anb rkvfgve ru qvsreragr qr rfgne inmvb.\n  - qribyir 0  REENQB. Anb rkvfgr rffr "inybe cnqenb".\n\nCbe vffb, dhnaqb ibpr anb grz pregrmn qr dhr n punir rfgn yn, crethagn\nnagrf: `vs \'ahzreb\' va raqrerpb_qn_zvegrf.xrlf():` - ru rkngnzragr b dhr n\nshapnb npubh_raqrerpb inv snmre, an Snfr 3, ceb PRC dhr anb rkvfgr.\n',
    'valor_do_erro': 'D - inybe_qb_reeb: b dhr ru b inybe qn punir \'reeb\'?\n\nN erfcbfgn dhr irvb sbv {\'reeb\': \'gehr\'}.\n\n  - n fgevat \'gehr\'  PBEERGB. Ercner anf nfcnf r an yrgen zvahfphyn:\n    \'gehr\' ru grkgb. B obbyrnab qb Clguba fr rfperir Gehr, pbz G\n    znvhfphyb r frz nfcnf.\n  - b obbyrnab Gehr  REENQB, r ru hzn neznqvyun pynffvpn qr NCV: dhrz\n    rfperirh b freivqbe znaqbh n cnynien rz grkgb, r anb b inybe\n    ybtvpb. Fr ibpr rfperire `vs erfcbfgn[\'reeb\'] == Gehr:` anb inv\n    shapvbane - n fgevat \'gehr\' anb ru vthny nb obbyrnab Gehr.\n  - b ahzreb 1  REENQB. Anb un ahzreb arauhz arffn erfcbfgn.\n\nRu cbe vffb dhr n shapnb npubh_raqrerpb crethagn fr n PUNIR irvb\n(`\'reeb\' va erfcbfgn.xrlf()`), rz irm qr byune b inybe qryn. N crethagn\n"irvb n punir \'reeb\'?" anb qrcraqr qr pbzb b freivqbe rfperirh b "gehr" -\nr pbagvahn shapvbanaqb fr hz qvn ryr zhqne qr vqrvn r znaqne Gehr qr\nireqnqr.\n',
    'qual_das_duas': 'D - dhny_qnf_qhnf: dhngeb crethagnf fboer b ZRFZB raqrerpb\n\nN crethagn anb ru "dhny qnf qhnf sbeznf shapvban" - nf qhnf shapvbanz r\nvzcevzrz n zrfzn pbvfn. Ru "dhny qnf qhnf ibpr dhre rfgne hfnaqb", r n\nqvsrerapn ru dhnagnf irmrf b cebtenzn inv nb IvnPRC ohfpne hz raqrerpb\ndhr ryr wn grz.\n\n  - onvkne HZN irm r cnffne b qvpvbanevb cnen nf dhngeb chenf  PBEERGB.\n    B raqrerpb qn Zvegrf ru hz fb. Qrcbvf qr onvknqb, erfcbaqre "dhny n\n    pvqnqr", "dhny n hs", "dhny b raqrerpb phegb" r "grz pbzcyrzragb" ru\n    fb yre b qvpvbanevb - arauhzn qrffnf dhngeb cerpvfn qr vagrearg.\n  - punzne nf dhngeb veznf  REENQB, r ru b reeb angheny: pnqn vezn\n    erfbyir fbmvaun, ragnb cnerpr znvf cengvpb. Fb dhr pnqn hzn qrynf\n    punzn ohfpn_prc cbe qrageb - dhngeb qbjaybnqf qb zrfzb raqrerpb. Ahzn\n    ghezn vagrven ebqnaqb b nedhvib n pnqn erfcbfgn cerrapuvqn, vffb iven\n    crqvqb qrznvf ceb zrfzb fvgr.\n  - gnagb snm, rfperirz n zrfzn dhnagvqnqr qr pbqvtb  REENQB. Ngr\n    rfperirz cnerpvqb - b dhr zhqn anb ru b gnznaub qb pbqvtb, ru b\n    ahzreb qr vqnf n vagrearg.\n  - veznf anf qhnf cevzrvenf r chenf anf bhgenf qhnf  REENQB. Zvfghene\n    anb erfbyir anqn: pbagvahnz fboenaqb qbvf qbjaybnqf qb zrfzb\n    raqrerpb, r nvaqn svpn qvsvpvy qr yre.\n\nN erten dhr fnv qvffb, r dhr inyr ceb erfgb qn yvfgn: n VEZN dhnaqb n\ncrethagn ru HZN fb r ibpr anb grz qvpvbanevb arauhz an znb; n CHEN\ndhnaqb fnb INEVNF crethagnf fboer b zrfzb qvpvbanevb (ru b pnqnfgeb qn\nSnfr 4). Ab pnqnfgeb.cl, b svany qn yvfgn, ibpr inv ire nf qhnf rz npnb:\nb zrah crethagn b PRC hzn irm r hfn n erfcbfgn cen ghqb - r n shapnb\ncerrapur_raqrerpb qryr ru, an cengvpn, n ohfpn_prc frthvqn qb vs/ryfr qn\nSnfr 3.\n\nRu gnzorz cbe vffb dhr raqrerpb_phegb r grz_pbzcyrzragb anb tnaunenz\nvezn: rynf fb ncnerprz baqr b qvpvbanevb wn rfgn an znb.\n',
    'complemento_do_cicero_a_mao': "D - pbzcyrzragb_qb_pvpreb_n_znb\n\nB pbzcyrzragb qb Pvpreb ru 'qr 971/972 n 1399/1400' - hzn fgevat pbz\npbagrhqb. Ragnb Gehr.\n\nPbzcner pbz b qn Zvegrf, dhr ru '' (fgevat inmvn). Abf qbvf pnfbf n PUNIR\n'pbzcyrzragb' rkvfgr; b dhr zhqn ru b inybe rfgne inmvb bh anb. Ru cbe\nvffb dhr n shapnb grz_pbzcyrzragb pbzcnen pbz '' rz irm qr crethagne fr n\npunir rkvfgr.\n",
    'mostra_clientes': 'D - zbfgen_pyvragrf (b "ire gbqbf" qb pnqnfgeb)\n\nR n zrfzn rfgehghen qn npun_pyvragr, fb dhr frz b erghea qr qrageb qb\nsbe:\n\n    qrs npun_pyvragr(pyvragrf, abzr):\n        sbe pyvragr va pyvragrf:\n            vs pyvragr[\'abzr\'].ybjre() == abzr.ybjre():\n                erghea pyvragr\n        erghea Abar\n\n    qrs zbfgen_pyvragrf(pyvragrf):\n        sbe qvpg_pyvragr va pyvragrf:\n            zbfgen_pyvragr(qvpg_pyvragr)\n\nB npun_pyvragr crepbeer n yvfgn cebphenaqb HZ pyvragr - dhnaqb npun, b\nerghea cnen b sbe an uben r qribyir b qvpvbanevb qryr. B zbfgen_pyvragrf\ncrepbeer n yvfgn VAGRVEN, cbedhr ndhv anb fr cebphen avathrz: pnqn\npyvragr qn yvfgn inv cen zbfgen_pyvragr, dhr vzcevzr n svpun qryr.\nArauhz erghea: n shapnb fb vzcevzr r grezvan.\n\nR b inmvb? Hz vs nagrf qb sbe:\n\n    vs pyvragrf == []:\n        cevag(\'  b pngnybtb rfgn inmvb\')\n        erghea\n\n`pyvragrf == []` pbzcnen n yvfgn vagrven pbz n yvfgn inmvn: ru Gehr\ndhnaqb anb fboebh avathrz. Frz rffr vs, b sbe fvzcyrfzragr anb ebqnevn -\nr b zrah svpnevn rz fvyrapvb, frz nivfne dhr anb un avathrz.\n',
    'status_certo_de_cep_que_nao_existe': 'D - fgnghf_pregb_qr_prc_dhr_anb_rkvfgr: dhny frevn b fgnghf PREGB?\n\nRfgn crethagn anb ru fboer b IvnPRC - ru fboer b CNQENB qn jro, ndhryr\ndhr n znvbevn qbf fvgrf r NCVf frthr.\n\n  - 404, "anb rkvfgr vffb dhr ibpr crqvh"  PBEERGB. N jro erfreibh b 404\n    rkngnzragr cen vffb: ibpr crqvh, r n pbvfn anb rkvfgr. Hz fvgr qr PRC\n    dhr frthvffr b cnqenb erfcbaqrevn 404 ceb 99999999.\n  - 200, "qrh pregb"  REENQB. B 200 qvm "qrh pregb, ndhv rfgn b dhr ibpr\n    crqvh". Cen hzn pbvfn dhr ANB RKVFGR, 200 frevn zragve: anb un anqn\n    cen ragertne.\n  - 500, "b freivqbe dhroebh"  REENQB. B 500 qvm dhr b FREIVQBE dhroebh -\n    hz qrsrvgb qb ynqb qr yn. Anb npune hz PRC anb ru qrsrvgb: ru erfcbfgn\n    abezny n hzn crethagn inyvqn.\n  - 204, "qrh pregb, znf anb grz pbagrhqb"  REENQB, znf ru hz cnycvgr obz:\n    b 204 freivevn fr n erfcbfgn ivrffr INMVN. B IvnPRC anb inv erfcbaqre\n    inmvb - rfcren cen ire.\n\nN yvpnb: nagrf qr byune b dhr b IvnPRC snm, dhny ru b pbzcbegnzragb dhr n\njro rafvan? 404. Thneqr vffb - n cebkvzn dhrfgnb inv crqve cen ibpr ire,\nab sversbk, b dhr RYR snm qr ireqnqr.\n',
    'status_viacep_de_cep_que_nao_existe': 'D - fgnghf_ivnprc_qr_prc_dhr_anb_rkvfgr: b dhr b sversbk zbfgen?\n\nPbzb noeve: S12 noer nf sreenzragnf qb qrfraibyirqbe; n non "Argjbex"\n(Erqr) yvfgn pnqn crqvqb dhr b anirtnqbe snm. Ryn cerpvfn rfgne NOREGN\nNAGRF qr anirtne - fr ibpr noeve qrcbvf qr n cntvan pneertne, n yvfgn\nsvpn inmvn. Ncregr S5 pbz ryn noregn r b crqvqb ncnerpr.\n\n  - 200, b zrfzb qr dhnaqb b PRC rkvfgr  PBEERGB. R ru whfgnzragr vffb dhr\n    gbean b IvnPRC rfgenaub: qb cbagb qr ivfgn qn jro, n erdhvfvpnb qrh\n    pregb - ryr gr ragertbh hzn erfcbfgn rz wfba, qvervgvaub. Dhr rffn\n    erfcbfgn fvtavsvdhr "anb npurv" ru pbvfn dhr fb ncnerpr QRAGEB qbf\n    qnqbf, an punir \'reeb\'.\n  - 404, frthvaqb b cnqenb qn jro  REENQB ndhv, znf ru n erfcbfgn dhr n\n    dhrfgnb nagrevbe gr srm rfcrene. N znvbevn qnf NCVf erfcbaqrevn 404\n    zrfzb. B IvnPRC rfpbyurh bhgeb pnzvaub.\n  - 500  REENQB. 500 dhre qvmre dhr b freivqbe DHROEBH - hz qrsrvgb qb\n    ynqb qr yn. Anb npune hz PRC anb ru qrsrvgb arauhz: ru hzn erfcbfgn\n    cresrvgnzragr abezny n hzn crethagn inyvqn.\n  - 204  REENQB, znf ru hz cnycvgr obz: 204 dhre qvmre "qrh pregb, r anb\n    grz pbagrhqb arauhz cen gr qribyire". Fr b IvnPRC qribyirffr erfcbfgn\n    INMVN ceb PRC varkvfgragr, 204 frevn n rfpbyun pregn. Fb dhr ryr\n    qribyir pbagrhqb - b {\'reeb\': \'gehr\'}.\n\nN yvpnb dhr svpn: **b ahzreb r bf qnqbf cbqrz qvfpbeqne**. Hz 200 anb\ncebzrgr dhr ibpr npubh b dhr dhrevn; cebzrgr fb dhr n pbairefn pbz b\nfreivqbe shapvbabh. Cbe vffb n shapnb npubh_raqrerpb byun n punir \'reeb\',\nr anb b fgnghf - fr byunffr b fgnghf, ryn qvevn dhr gbqb PRC rkvfgr.\n',
    'por_que_o_json_estourou': 'D - cbe_dhr_b_wfba_rfgbhebh: b PRC \'123\' r b WFBAQrpbqrReebe\n\n  - cbedhr b .wfba() gragn yre b pbecb pbzb qvpvbanevb, r b pbecb ren hzn\n    cntvan UGZY  PBEERGB. B .wfba() snm hzn pbvfn fb: crtn b grkgb dhr\n    irvb r gragn vagrecergne pbzb wfba. B grkgb dhr irvb pbzrpnin pbz\n    \'<!QBPGLCR UGZY>\' - r nv ryr erpynzn qb cevzrveb pnenpgrer, dhr ru\n    rkngnzragr b dhr n zrafntrz qvm: "Rkcrpgvat inyhr: yvar 1 pbyhza 1".\n  - cbedhr b PRC \'123\' anb rkvfgr  REENQB, r n qvsrerapn ru svan znf\n    vzcbegnagr: \'123\' anb ru hz PRC dhr anb rkvfgr, ru hzn pbvfn dhr arz\n    purtn n fre hz PRC (PRC grz 8 qvtvgbf). B dhr ANB RKVFGR znf ru orz\n    sbeznqb - b 99999999 - ibygn 200 pbz wfba pregvaub, r b .wfba() anb\n    erpynzn anqn.\n  - cbedhr b erdhrfgf erphfn PRC pbz zrabf qr 8 qvtvgbf  REENQB. B\n    erdhrfgf anb fnor b dhr ru hz PRC; ryr crqr n hey dhr ibpr znaqbh r\n    ragertn b dhr ibygne. Dhrz erpynzbh qb gnznaub sbv b IvnPRC.\n  - cbedhr b fgnghf 400 snm b .wfba() yrinagne reeb fbmvaub  REENQB, r ru\n    n nygreangvin dhr inyr cerfgne ngrapnb: b .wfba() ANB byun b fgnghf. N\n    cebin ru dhr rkvfgr NCV dhr qribyir wfba obavgb whagb qr hz 400 - r nv\n    b .wfba() shapvban abeznyzragr. Dhrz rfgbhebh sbv b PBAGRHQB, anb b\n    ahzreb.\n\nWhagr pbz n dhrfgnb nagrevbe r ibpr grz nf qhnf zrgnqrf: b ahzreb r b\npbagrhqb fnb pbvfnf FRCNENQNF. Hz 200 cbqr genmre "anb npurv" qrageb qbf\nqnqbf, r hz 400 cbqr genmre hzn cntvan UGZY baqr ibpr rfcrenin\nqvpvbanevb.\n',
}
