"""Explicacoes das questoes de multipla escolha - agenda.

O conteudo esta em ROT13 de proposito: visivel no arquivo, mas
ilegivel a olho nu, para nao entregar a resposta a quem so rola o
arquivo. A funcao explicar() do exercicio decodifica e imprime.

NAO edite este arquivo a mao - ele eh gerado por
NAO_MANDAR_montar_explicacao_agenda.py.
"""

EXPLICACOES = {
    'acesso_chave': 'D - nprffb_punir: b dhr `ntraqn_rkrzcyb[\'znevn\']` ergbean?\n\nB grkgb qrsvavh: ibpr pbybpn hzn PUNIR rager pbypurgrf, r b qvpvbanevb\nqribyir b INYBE thneqnqb arffn punir. An ntraqn, n punir ru n crffbn r b\ninybe ru b gryrsbar qryn.\n\n  - b gryrsbar qn znevn (b inybe thneqnqb an punir \'znevn\')  PBEERGB.\n    \'znevn\' ru hzn punir qn ntraqn; rager pbypurgrf ryn qribyir b inybe\n    nffbpvnqb - b gryrsbar.\n  - n cbfvpnb qn znevn  REENQB. Qvpvbanevb anb grz "cbfvpbrf" pbzb n yvfgn.\n    B pbypurgr erpror n punir, anb hz ahzreb qr cbfvpnb.\n  - reeb cbedhr \'znevn\' anb ru hz ahzreb  REENQB. Whfgnzragr b pbagenevb:\n    n inagntrz qb qvpvbanevb ru dhr n punir cbqr fre hzn fgevat.\n  - b abzr \'znevn\'  REENQB. \'znevn\' ru b dhr ibpr WN pbybpbh rager\n    pbypurgrf (n punir). B dhr ibygn ru b INYBE - b gryrsbar.\n',
    'acesso_valor': 'D - nprffb_inybe: b dhr npbagrpr pbz `ntraqn_rkrzcyb[44554455]`?\n\nPhvqnqb: 44554455 ru b GRYRSBAR qn znevn, bh frwn, hz INYBE qn ntraqn - anb\nhzn punir. B grkgb qvffr dhr rager pbypurgrf inv hzn PUNIR. Cebphene cbe hz\ninybe rager pbypurgrf anb npun anqn.\n\n  - XrlReebe: 44554455 anb ru hzn PUNIR qn ntraqn (ru hz inybe)  PBEERGB.\n    B qvpvbanevb cebphen 44554455 rager nf PUNIRF (\'znepbf\', \'snovb\',\n    \'znevn\') r anb rapbagen -> reeb (XrlReebe).\n  - ergbean \'znevn\'  REENQB. B qvpvbanevb anb snm n ohfpn "nb pbagenevb"\n    (qr inybe cnen punir). Pbypurgr frzcer cebphen rager nf PUNIRF.\n  - ergbean b gryrsbar qn znevn  REENQB. Vffb frevn cebphene cryn punir\n    \'znevn\'. Ndhv ibpr pbybpbh b gryrsbar, anb n punir.\n  - ergbean 0  REENQB. Ibpr qrh hzn punir dhr anb rkvfgr, r b qvpvbanevb qrh\n    reeb. Yrzoer-fr gnzorz dhr anb un arauhz 0 arffr qvpvbanevb, cbedhr\n    qvpvbanevbf anb grz cbfvpbrf 0,1,2 pbzb anf yvfgnf.\n',
    'acesso_posicao': 'D - nprffb_cbfvpnb: b dhr npbagrpr pbz `ntraqn_rkrzcyb[0]`?\n\nNdhv rfgn n qvsrerapn prageny rager yvfgn r qvpvbanevb. Ahzn yvfgn,\nyvfgn[0] ru b cevzrveb ryrzragb (cbfvpnb 0). Ahz qvpvbanevb ANB rkvfgrz\ncbfvpbrf - fb rkvfgrz nf punirf dhr ibpr pevbh. B grkgb qvffr: rager\npbypurgrf inv hzn PUNIR.\n\n  - XrlReebe: qvpvbanevb anb grz cbfvpbrf; 0 anb ru punir qn ntraqn  PBEERGB.\n    Nf punirf fnb \'znepbf\', \'snovb\', \'znevn\'. B ahzreb 0 anb ru arauhzn\n    qrynf -> XrlReebe.\n  - ergbean b gryrsbar qb znepbf (cevzrven crffbn)  REENQB. Vffb ru\n    crafnzragb qr YVFGN ("cbfvpnb 0 = cevzrveb"). Qvpvbanevb anb vaqrkn cbe\n    cbfvpnb.\n  - ergbean \'znepbf\'  REENQB. Zrfzb ratnab: qvpvbanevb anb grz "ryrzragb qn\n    cbfvpnb 0".\n  - ergbean n ntraqn vagrven  REENQB. Pbypurgr frzcer gragn npune HZN punir,\n    ahapn qribyir n ntraqn gbqn.\n',
    'criar_chave_nova': 'D - pevne_punir_abin: pbzb pevne hzn punir ABIN ahz qvpvbanevb?\n\nAhzn YVFGN, cnen perfpre ibpr hfn `.nccraq(...)` - n yvfgn anb grz\n"cbfvpnb abin" ngr ibpr nperfpragne. Ab QVPVBANEVB ru qvsreragr r znvf\nfvzcyrf: onfgn NGEVOHVE n hzn punir dhr nvaqn anb rkvfgr, r ryn cnffn n\nrkvfgve.\n\n  - ntraqn[\'nan\'] = 555  PBEERGB. Ngevohve qvergb n hzn punir varkvfgragr\n    PEVN n punir \'nan\' pbz b inybe 555. Anb cerpvfn qr arauhz zrgbqb\n    rfcrpvny.\n  - ntraqn.nccraq(\'nan\', 555)  REENQB. `.nccraq` ru qr YVFGN, anb qr\n    qvpvbanevb. Qvpvbanevb arz grz rffr zrgbqb (qnevn NggevohgrReebe).\n  - ntraqn[\'nan\'].nccraq(555)  REENQB. Vffb gragnevn hfne `ntraqn[\'nan\']`\n    nagrf qn punir \'nan\' rkvfgve (XrlReebe) - r znvf dhr vffb, b inybe\n    nffbpvnqb n punir nan cerpvfnevn fre hzn yvfgn, cbedhr fb yvfgn\n    grz b pbznaqb nccraq.\n  - n ngevohvpnb R b nccraq shapvbanz  REENQB. N ngevohvpnb shapvban, znf b\n    nccraq anb - ragnb "bf qbvf" anb cbqr rfgne pregb. Rffn nygreangvin crtn\n    dhrz npregbh n ngevohvpnb znf svpbh an qhivqn fr b nccraq gnzorz inyrevn\n    "cbe ivn qnf qhivqnf". Inyr fb hz: n ngevohvpnb.\n  - bf gerf shapvbanz  REENQB. Cryb zrfzb zbgvib, r nvaqn znvf sbegr: qbvf\n    qbf gerf hfnz `.nccraq`, dhr qvpvbanevb anb grz. Fr bf gerf shapvbanffrz,\n    anb unirevn qvsrerapn arauhzn rager yvfgn r qvpvbanevb - r n yvfgn gbqn\n    ru fboer rffn qvsrerapn.\n',
    'precisa_reatribuir': "D - cerpvfn_erngevohve: cerpvfb erngevohve `ntraqn = nqvpvban(...)`?\n\nPbzcner pbz b fnyqb qb rkrepvpvb qr ncbfgnf: ahzreb ru VZHGNIRY, ragnb n\nshapnb gvaun dhr ERGBEANE b abib fnyqb r ibpr ERNGEVOHVN. Qvpvbanevb ru b\nbcbfgb: ru ZHGNIRY, vthny n yvfgn pbz `.nccraq`. N shapnb zrkr ab cebcevb\nqvpvbanevb dhr ibpr cnffbh.\n\nInyr n cran pbybpne ire an ncbfgvyn n shapnb nqvpvban ab clgubaghgbe\nr ire dhr ryn grz n 'frgvaun' cebf qvpvbanevbf -- n zrfzn frgvaun\ndhr nagrf ncnerpvn cen yvfgnf\n\nNygreangvinf:\n\n  - fvz, franb n zhqnapn fr creqr  REENQB. Vffb inyrevn cen hz ahzreb\n    (vzhgniry). B qvpvbanevb ru zhgniry: n nygrenpnb npbagrpr aryr zrfzb.\n  - anb - qvpg ru ZHGNIRY; onfgn punzne nqvpvban(...)  PBEERGB. N shapnb snm\n    `ntraqn[crffbn] = gryrsbar` ab qvpvbanevb dhr irvb cbe cnenzrgeb - b\n    zrfzb dhr rfgn yn sben. Punzne nqvpvban(...) wn onfgn.\n  - fb fr n punir wn rkvfgve  REENQB. Rkvfgvaqb bh anb n punir, n zhgnpnb\n    npbagrpr ab cebcevb qvpvbanevb. Ahapn cerpvfn erngevohve.\n",
    'chave_repetida': 'D - punir_ercrgvqn: \'nan\' wn inyr 555; qrcbvf qr nqvpvban(ntraqn,\'nan\',999)?\n\nBhgen qvsrerapn cnen n yvfgn. `yvfgn.nccraq` FRZCER nperfpragn - fr ibpr\nqre nccraq qhnf irmrf, b ryrzragb ncnerpr qhnf irmrf. Qvpvbanevb ANB\nqhcyvpn punir: pnqn punir rkvfgr hzn irm fb. Ngevohve qr abib FBOERFPERIR b\ninybe nagvtb.\n\n  - 555 (b cevzrveb irapr)  REENQB. B inybe nagvtb anb "tnaun"; ryr ru\n    fhofgvghvqb cryb abib.\n  - 999 r 555 svpnz bf qbvf thneqnqbf  REENQB. Vffb frevn pbzcbegnzragb qr\n    yvfgn. Qvpvbanevb thneqn HZ inybe cbe punir.\n  - 999 - fboerfperir b inybe nagvtb  PBEERGB. `ntraqn[\'nan\'] = 999` gebpn b\n    inybe qn punir \'nan\' qr 555 cnen 999. N punir pbagvahn havpn.\n',
    'init_contador': "D - vavg_pbagnqbe: pbzb pevne b pbagnqbe vavpvny?\n\nInzbf PBAFGEHVE b qvpvbanevb qb mreb, nqvpvbanaqb hzn punir cbe yrgen n\nzrqvqn dhr crepbeerzbf n cnynien. Ab pbzrpb ryr rfgn inmvb.\n\n  - pbagnqbe = {}  PBEERGB. `{}` ru b qvpvbanevb inmvb. Qnyv rz qvnagr n\n    tragr pevn nf punirf (hzn cbe yrgen) pbz `pbagnqbe[yrgen] = ...`.\n  - pbagnqbe = []  REENQB. `[]` ru hzn YVFGN inmvn. Qnevn cen qne nccraq,\n    znf anb qn cen snmre `pbagnqbe['n'] = ...` (yvfgn anb vaqrkn cbe\n    fgevat).\n  - pbagnqbe = 0  REENQB. Hz ahzreb anb thneqn punir arauhzn; `pbagnqbe['n']`\n    arz snm fragvqb.\n  - pbagnqbe = ['']  REENQB. Vffb ru hzn yvfgn pbz hzn fgevat inmvn qrageb,\n    anb hz qvpvbanevb inmvb.\n",
    'letra_nova': 'D - yrgen_abin: nb ire hzn yrgen dhr nvaqn ANB rfgn ab pbagnqbe?\n\nN cevzrven irm dhr hzn yrgen ncnerpr, ryn nvaqn anb grz pbagntrz. Nagrf qr\nfbzne, cerpvfnzbf PEVNE n punir qryn pbzrpnaqb qb mreb - qnv b `+ 1`\nfrthvagr yrin ryn n 1.\n\n  - pbagnqbe[yrgen] = 1  REENQB (dhnfr). Shapvbanevn cbe npnfb arfgn yrgen,\n    znf ngencnyun b qrfraub: n vqrvn ru "pbzrpne rz 0 r qrvkne b vaperzragb\n    snmre b +1". Fr ibpr wn cbr 1 ndhv R vaperzragn qrcbvf, pbagn 2 an\n    cevzrven ncnevpnb.\n  - pbagnqbe[yrgen] = 0  PBEERGB. Pevn n punir qn yrgen inyraqb 0. Ybtb rz\n    frthvqn b vaperzragb fbzn 1 r ryn svpn pbz 1.\n  - pbagnqbe.nccraq(yrgen)  REENQB. `.nccraq` ru qr yvfgn; qvpvbanevb anb\n    grz. R anb thneqnevn pbagntrz arauhzn.\n  - pbagnqbe[0] = yrgen  REENQB. Vffb hfn 0 pbzb PUNIR r thneqn n yrgen pbzb\n    inybe - b bcbfgb qb dhr dhrerzbf (n yrgen ru n punir, n pbagntrz ru b\n    inybe).\n',
    'por_que_checar': 'D - cbe_dhr_purpne: cbe dhr cerpvfnzbf qb "fr n yrgen nvaqn ANB rfgn..."?\n\nVzntvar gvene rffn purpntrz r snmre `pbagnqbe[yrgen] = pbagnqbe[yrgen] + 1`\nqvergb. An CEVZRVEN irm dhr hzn yrgen ncnerpr, b ynqb qvervgb yr\n`pbagnqbe[yrgen]` - znf rffn punir nvaqn anb rkvfgr.\n\n  - anqn zhqn, shapvban vthny  REENQB. Frz pevne n punir nagrf, n cevzrven\n    yrvghen wn dhroen.\n  - an 1n irm, pbagnqbe[yrgen] qn XrlReebe (n punir nvaqn anb rkvfgr)\n    PBEERGB. Yre hzn punir varkvfgragr yrinagn XrlReebe. Cbe vffb pevnzbf n\n    punir rz 0 NAGRF qr vaperzragne.\n  - b cebtenzn svpn yragb  REENQB. Anb ru dhrfgnb qr irybpvqnqr; ru reeb\n    (XrlReebe) ybtb an cevzrven yrgen.\n  - pbagn ghqb rz qboeb  REENQB. Anb purtn n pbagne reenqb: b cebtenzn cnen\n    pbz reeb nagrf qvffb.\n',
    'como_checar': 'D - pbzb_purpne: pbzb fr RFPERIR "fr n yrgen nvaqn ANB rfgn ab pbagnqbe"?\n\nN dhrfgnb nagrevbe rkcyvpbh cbe dhr n purpntrz rkvfgr (frz ryn, n cevzrven\nyrvghen qr hzn yrgen abin qn XrlReebe). Ntben ru fb genqhmve. Qhnf pbvfnf\ncnen npregne: cebphene qb ynqb qnf PUNIRF (n yrgen ru punir qb pbagnqbe, anb\ninybe) r ab qvpvbanevb PREGB (b pbagnqbe, anb n cnynien).\n\n  - vs yrgen abg va pbagnqbe.xrlf()  PBEERGB. `pbagnqbe.xrlf()` qn nf yrgenf\n    wn ivfgnf; `abg va` crethagn fr rfgn yrgen nvaqn anb ncnerprh. Ru n zrfzn\n    sbezn qn Snfr 1, fb dhr ntben pbz b pbagnqbe ab yhtne qn ntraqn.\n  - vs pbagnqbe[yrgen] == 0  REENQB, r ru b ratnab znvf gragnqbe: rffn yvaun\n    WN YR `pbagnqbe[yrgen]`, dhr ru rkngnzragr b dhr n dhrfgnb nagrevbe qvffr\n    dhr dhroen dhnaqb n punir anb rkvfgr. Bh frwn, ryn qn XrlReebe an\n    cevzrven irm dhr n yrgen ncnerpr - b ceboyrzn dhr n purpntrz qrivn\n    rivgne. Nyrz qvffb, n pbagntrz ahapn svpn rz 0 qrcbvf qb vaperzragb, fb\n    ybtb nagrf qryr.\n  - vs yrgen abg va pbagnqbe.inyhrf()  REENQB. `.inyhrf()` qn nf PBAGNTRAF\n    (ahzrebf pbzb 1, 2, 3), anb nf yrgenf. Cebphene n yrgen \'o\' rager bf\n    ahzrebf anb npun ahapn - ragnb b grfgr qnevn Gehr frzcer, r n punir frevn\n    mrenqn n pnqn ibygn. N yrgen ru PUNIR qb pbagnqbe; dhrz cebphen punir ru\n    `.xrlf()`.\n  - vs yrgen abg va cnynien  REENQB. Qvpvbanevb gebpnqb: n yrgen irvb WHFGB\n    qr crepbeere n cnynien, ragnb ryn frzcer rfgn an cnynien r b grfgr qnevn\n    Snyfr frzcer - n punir ahapn frevn pevnqn, r nv b vaperzragb dhroen. N\n    crethagn ru fboer b PBAGNQBE, anb fboer n cnynien.\n',
    'incremento': 'D - vaperzragb: pbzb fbzne 1 an pbagntrz qn yrgen?\n\nN punir qn yrgen wn rkvfgr (bh cbedhr wn ncnerprh nagrf, bh cbedhr n yvaun\nnagrevbe pevbh rz 0). Ntben dhrerzbf n pbagntrz nghny ZNVF 1, thneqnqn qr\nibygn an zrfzn punir.\n\n  - pbagnqbe[yrgen] = pbagnqbe[yrgen] + 1  PBEERGB. Yr n pbagntrz nghny qn\n    yrgen, fbzn 1, r thneqn qr ibygn an punir qn yrgen. (`pbagnqbe[yrgen] += 1`\n    ru n sbezn phegn qn zrfzn pbvfn.)\n  - pbagnqbe[yrgen] = 1  REENQB. Vffb MREN n uvfgbevn: gbqn irm cbevn 1,\n    ragnb gbqn yrgen grezvanevn pbz 1 - anb pbagn ercrgvpbrf.\n  - pbagnqbe = pbagnqbe + 1  REENQB. Gragn fbzne 1 nb qvpvbanevb vagrveb\n    (GlcrReebe). N tragr fbzn an pbagntrz qr HZN yrgen, anb ab qvpg gbqb.\n  - pbagnqbe.nccraq(yrgen)  REENQB. `.nccraq` ru qr yvfgn; r anb fbzn\n    pbagntrz arauhzn.\n',
    'retorno': 'D - ergbeab: b dhr n shapnb qrir ergbeane ab svz?\n\nN shapnb pbagn_yrgenf cebzrgr qribyire b QVPVBANEVB qr pbagntraf\n(yrgen -> dhnagnf irmrf). Rffr qvpvbanevb ru rkngnzragr b `pbagnqbe` dhr n\ntragr sbv zbagnaqb.\n\n  - erghea yrgen  REENQB. `yrgen` ru fb n hygvzn yrgen ivfgn ab ynpb - anb n\n    pbagntrz.\n  - erghea yra(pbagnqbe.xrlf())  REENQB. Vffb qribyir DHNAGNF punirf qvsreragrf\n    rkvfgrz (dhnagnf yrgenf qvfgvagnf), anb b zncn qr pbagntraf.\n  - erghea pbagnqbe  PBEERGB. Qribyir b qvpvbanevb zbagnqb, pbz pnqn yrgen\n    ncbagnaqb cnen fhn pbagntrz.\n  - erghea cnynien  REENQB. Qribyirevn n cnynien bevtvany, frz pbagntrz\n    nythzn.\n',
}
