"""Explicacoes das questoes - viagem.

O conteudo esta em ROT13 de proposito: visivel no arquivo, mas
ilegivel a olho nu, para nao entregar a resposta a quem so rola o
arquivo. A funcao explicar() do exercicio decodifica e imprime.

NAO edite este arquivo a mao - ele eh gerado por
NAO_MANDAR_montar_explicacao_viagem.py.
"""

EXPLICACOES = {
    'cotacao_do_euro': "D - pbgnpnb_qb_rheb\n\nNf pbgnpbrf anb rfgnb fbygnf ab gbcb qb qvpvbanevb: rfgnb gbqnf qrageb qb\nqvpvbanevb dhr zben an punir 'engrf'. Fnb qbvf cnffbf:\n\n    pnzovb_whyub['engrf']          ->  {'RHE': 0.16662, 'WCL': ..., 'HFQ': ...}\n    pnzovb_whyub['engrf']['RHE']   ->  0.16662\n\nReeb pbzhz: pnzovb_whyub['RHE'] - qn XrlReebe, cbedhr 'RHE' ru punir qb\nqvpvbanevb qr QRAGEB; b qr pvzn anb grz rffn punir.\n\nAnb pbashaqn pbz 'nzbhag': 1.0, dhr ru bhgen pbvfn - ru n dhnagvqnqr qr\nernvf fboer n dhny n pbgnpnb sbv pnyphynqn (hz).\n",
    'moeda_base': "D - zbrqn_onfr\n\n    pnzovb_whyub['onfr']   ->  'OEY'\n\nRffn rfgn ab gbcb zrfzb, pbz hz pbypurgr fb. 'OEY' ru b pbqvtb\nvagreanpvbany qb erny - ru n zbrqn dhr ibpr GRZ, n dhr freir qr cbagb qr\ncnegvqn cnen gbqnf nf pbgnpbrf dhr ivrenz rz 'engrf'.\n\nReeb pbzhz: erfcbaqre 'RHE', dhr ru n zbrqn dhr n Uryran dhre. Rffn\nncnerpr pbzb PUNIR qrageb qr 'engrf', anb pbzb onfr. Sbv ibpr dhr\nrfpbyurh nf qhnf, ab raqrerpb: b `sebz=OEY` ivebh b 'onfr', r b\n`gb=RHE,HFQ,WCL` ivebh nf punirf qr 'engrf'.\n",
    'data_do_cambio': "D - qngn_qb_pnzovb\n\n    pnzovb_whyub['qngr']   ->  '2024-07-01'\n\nErcner dhr n erfcbfgn ru hzn FGEVAT, pbz nf nfcnf r bf genpvaubf qb wrvgb\ndhr irvb: '2024-07-01'. Anb ru b ahzreb 20240701 arz hzn qngn rfpevgn\n'01/07/2024'.\n\nRffn punir vzcbegn znvf qb dhr cnerpr: ru ryn dhr qvm dhr rffnf pbgnpbrf\nfnb qr hz qvn dhr wn cnffbh - r cbe vffb anb zhqnz znvf. Ru b dhr crezvgr\nb nffreg pbz b ahzreb rkngb ybtb npvzn, r gbqnf nf erfcbfgnf qr qvaurveb\nqrfgn yvfgn.\n\nPbzcner pbz b pnzovb_qr_ubwr: yn b 'qngr' ru n qngn qr ubwr, r nznaun\nfren bhgen.\n",
    'quantas_chaves_no_cambio': "D - dhnagnf_punirf_ab_pnzovb\n\nN crethagn ru fboer b qvpvbanevb qr PVZN, b pnzovb_whyub vagrveb - anb\nfboer b dhr rfgn qrageb qryr.\n\n    yra(pnzovb_whyub.xrlf())   ->  4\n\nNf dhngeb fnb: 'nzbhag', 'onfr', 'qngr' r 'engrf'.\n\nReeb pbzhz: erfcbaqre 3, pbagnaqb nf zbrqnf. Nf zbrqnf rfgnb hz aviry\nnonvkb, qrageb qr 'engrf' - r 'engrf' vagrveb inyr HZN punir, cbe znvbe\ndhr frwn b qvpvbanevb craqhenqb aryn.\n\nBhgeb reeb pbzhz: pbagne nf yvaunf dhr ncnerprz ab anirtnqbe. Hz\nqvpvbanevb dhr bphcn inevnf yvaunf pbagvahn fraqb hzn punir fb.\n",
    'quantas_moedas': "D - dhnagnf_zbrqnf\n\nNtben fvz n crethagn ru fboer b qvpvbanevb qr qrageb: dhnagnf zbrqnf\nivrenz ru dhnagnf punirf grz b 'engrf'.\n\n    yra(pnzovb_whyub['engrf'].xrlf())   ->  3\n\nNf gerf fnb 'RHE', 'WCL' r 'HFQ' - rkngnzragr nf dhr ibpr crqvh ab\n`gb=RHE,HFQ,WCL`.\n\nReeb pbzhz: yra(pnzovb_whyub.xrlf()) -> 4. Vffb pbagn nf punirf qb gbcb\n('nzbhag', 'onfr', 'qngr', 'engrf'), dhr anb fnb zbrqnf.\n",
    'o_que_o_json_devolve': 'D - b_dhr_b_wfba_qribyir: b dhr `erdhrfgf.trg(hey).wfba()` qribyir?\n\nFnb qhnf pbvfnf rz frdhrapvn. `erdhrfgf.trg(hey)` inv yn r ohfpn. B\n`.wfba()` crtn b dhr irvb (dhr ru grkgb) r ZBAGN n rfgehghen Clguba\npbeerfcbaqragr - ab pnfb qrfgnf qhnf NCVf, hz qvpvbanevb.\n\n  - hz qvpvbanevb  PBEERGB. Cbe vffb n yvfgn vagrven ru fb yrvghen qr\n    qvpvbanevb: qrcbvf qb .wfba() ibpr rfgn rz greevgbevb pbaurpvqb.\n  - b grkgb qn cntvan rz UGZY  REENQB. Vffb frevn hzn cntvan qr fvgr.\n    NCV anb qribyir cntvan, qribyir qnqb. (Fr ibpr dhvfrffr b grkgb peh,\n    nv fvz rkvfgr hz `.grkg` - znf anb ru b dhr hfnzbf.)\n  - hzn yvfgn  REENQB ndhv. Rkvfgrz NCVf dhr qribyirz yvfgn ab gbcb, r\n    ibpr inv ire hzn ab qrfnsvb (n ohfpn cbe abzr qr pvqnqr). Znf nf qhnf\n    NCVf qb pnzvaub cevapvcny qribyirz qvpvbanevb. Qn cen pbasreve\n    byunaqb b anirtnqbe: n erfcbfgn pbzrpn pbz `{`, anb pbz `[`.\n  - b raqrerpb qb fvgr  REENQB. B raqrerpb ru b dhr ibpr ZNAQN; b dhr\n    ibygn ru n erfcbfgn.\n',
    'chave_que_nao_existe': 'D - punir_dhr_anb_rkvfgr: r `pnzovb_whyub[\'engrf\'][\'TOC\']`?\n\n  - yrinagn XrlReebe r b cebtenzn cnen  PBEERGB. Crqve hzn punir dhr anb\n    rkvfgr ru hz reeb, r reeb rz Clguba vagreebzcr b cebtenzn. N zrafntrz\n    irz pbz b abzr qn punir: XrlReebe: \'TOC\'.\n  - qribyir Abar  REENQB, r ru n pbashfnb znvf pbzhz: dhrz qribyir Abar\n    rz irm qr dhroene ru b zrgbqb `.trg`\n    (pnzovb_whyub[\'engrf\'].trg(\'TOC\') -> Abar). B pbypurgr anb creqbn.\n  - qribyir hzn fgevat inmvn  REENQB. Anb rkvfgr rffr "inybe cnqenb".\n  - qribyir 0  REENQB, cryb zrfzb zbgvib. Frevn pbairavragr cnen\n    qvaurveb, znf b Clguba anb vairagn inybe arauhz.\n\nErcner cbe dhr n yvoen anb rfgn yn: ibpr anb crqvh. B raqrerpb qvmvn\n`gb=RHE,HFQ,WCL`, r n erfcbfgn genm b dhr sbv crqvqb, anqn znvf. Cen gre\nn yvoen, ren fb cbe TOC ab raqrerpb.\n\nCbe vffb, dhnaqb ibpr anb grz pregrmn qr dhr n punir rfgn yn, crethagn\nnagrf: `vs \'TOC\' va pnzovb_whyub[\'engrf\'].xrlf():` - dhr ru rkngnzragr b\ndhr n shapnb zbrqn_qvfcbaviry inv snmre.\n',
    'cambio_do_passado': 'D - pnzovb_qb_cnffnqb: cbe dhr qn cen pbasreve b inybe rkngb qr 2024-07-01?\n\n  - cbedhr ndhryr qvn wn cnffbh, r n pbgnpnb qryr anb zhqn znvf  PBEERGB.\n    B pnzovb qr hz qvn rfcrpvsvpb ru uvfgbevn: sbv ertvfgenqb hzn irm r\n    svpn. Crpn rffr raqrerpb ubwr, nab dhr irz bh qndhv n qrm nabf - irz\n    0.16662.\n  - cbedhr b rheb rfgn cnenqb qrfqr 2024  REENQB. Ryr inevn gbqb qvn -\n    gnagb dhr b `yngrfg` qn bhgeb ahzreb, r ibpr npnobh qr onvkne bf\n    qbvf. B dhr rfgn cnenqb ru b ERTVFGEB qndhryr qvn.\n  - cbedhr n NCV vairagn hz ahzreb svkb dhnaqb n qngn ru nagvtn  REENQB.\n    Ryn anb vairagn anqn; qribyir b dhr b Onapb Prageny Rhebcrh choyvpbh\n    andhryr qvn.\n\nRffn cebcevrqnqr ru n enmnb qr rfgn yvfgn pbzrpne cryb pnzovb, r anb\ncryb pyvzn. Pbzb b qvpvbanevb qr 2024-07-01 ru frzcer b zrfzb, qn cen\nONVKNE qr ireqnqr ab cevzrveb rkrepvpvb r nvaqn nffvz gre crethagnf pbz\nerfcbfgn svkn. Pbz b pyvzn vffb anb qnevn - ru b nffhagb qn dhrfgnb\ncbe_dhr_snvkn, znvf cen seragr.\n',
    'o_que_significa_a_cotacao': 'D - b_dhr_fvtavsvpn_n_pbgnpnb: b dhr dhre qvmre \'RHE\': 0.16662?\n\nN punir qn yrvghen ru b \'onfr\': \'OEY\'. Ghqb rz \'engrf\' rfgn qvgb "n\ncnegve qr 1 erny".\n\n  - 1 erny pbzcen 0.16662 rhebf  PBEERGB. Cbe vffb n pbagn ru\n    zhygvcyvpne: 1000 ernvf pbzcenz 1000 * 0.16662 = 166.62 rhebf.\n  - 1 rheb phfgn 0.16662 ernvf  REENQB, r ru b reeb dhr rfgentn n pbagn -\n    ru n yrvghen qr pnorpn cen onvkb. Fr sbffr nffvz, b rheb rfgnevn znvf\n    ONENGB dhr b erny, r 1000 ernvf pbzcenevnz znvf qr 6000 rhebf. (B\n    ahzreb pregb qrffr wrvgb frevn 1 / 0.16662, znvf bh zrabf 6 ernvf cbe\n    rheb - b dhr snm fragvqb pbz n ivqn erny.)\n  - n Uryran grz 0.16662 rhebf  REENQB. N NCV anb fnor dhnagb avathrz\n    grz; ryn fb choyvpn n pbgnpnb qb qvn.\n  - b rheb fhovh 0.16662% andhryr qvn  REENQB. Rffn erfcbfgn anb genm\n    inevnpnb arauhzn - fb b inybe.\n',
    'euros_de_1000_reais': 'D - rhebf_qr_1000_ernvf\n\nRfperin n pbagn, anb b erfhygnqb. Fr 1 erny pbzcen 0.16662 rhebf, 1000\nernvf pbzcenz zvy irmrf vffb:\n\n    ebhaq(1000 * 0.16662, 2)   ->  166.62\n\nB ebhaq(ahzreb, pnfnf) neerqbaqn cen ndhryr gnagb qr pnfnf qrpvznvf - 2,\ncbedhr ru qvaurveb. Ndhv 1000 * 0.16662 wn qn 166.62 pregvaub, ragnb b\nebhaq anb zhqn anqn; ryr inv snmre qvsrerapn ab pbairegr, dhnaqb n\nzhygvcyvpnpnb fnve pbz yvkb ab svz (gvcb 416.54999999999995).\n\nReeb pbzhz: qvivqve rz irm qr zhygvcyvpne (1000 / 0.16662 = 6001.6...).\nVffb erfcbaqr bhgen crethagn - dhnagbf ernvf pbzcenevnz 1000 rhebf.\nPbasven frzcer cryn beqrz qr tenaqrmn: b rheb inyr znvf dhr b erny, ragnb\nb ahzreb qr rhebf GRZ dhr fre zrabe dhr b qr ernvf.\n',
    'ienes_de_1000_reais': 'D - vrarf_qr_1000_ernvf\n\nZrfzn pbagn, bhgen pbgnpnb - qr abib pbzb rkcerffnb:\n\n    ebhaq(1000 * 28.851, 2)   ->  28851.0\n\nB ahzreb nffhfgn qrcbvf qr ire 166.62 rz rhebf, znf rfgn pregb: b vrar ru\nhzn zbrqn "crdhran", r 1 erny pbzcen dhnfr 29 qryrf. Hz pnsr rz Gbdhvb\nphfgn hznf pragranf qr vrarf.\n\nErcner dhr n ZRFZN shapnb (b pbairegr, ybtb nonvkb) inv snmre nf qhnf\npbagnf. B dhr zhqn ru fb n pbgnpnb dhr ryn crtn ab qvpvbanevb - r ru cbe\nvffb dhr n yvfgn rfpbyurh qhnf zbrqnf qr beqraf qr tenaqrmn gnb\nqvsreragrf.\n',
    'unidade_da_temperatura': "D - havqnqr_qn_grzcrenghen\n\nRffn ru n crtnqvaun qb cne qr qvpvbanevbf trzrbf. N erfcbfgn qn NCV grz\nQBVF qvpvbanevbf pbz nf zrfznf punirf cbe qrageb:\n\n    'pheerag_jrngure'        b dhr rfgn npbagrpraqb   -> 25.7\n    'pheerag_jrngure_havgf'  rz dhr havqnqr           -> '°P'\n\nRagnb:\n\n    pyvzn_yvfobn['pheerag_jrngure_havgf']['grzcrengher']   ->  '°P'\n\nFr ibpr sbv ab 'pheerag_jrngure', crtbh b ahzreb - r ryr zhqn n pnqn 15\nzvahgbf, ragnb anb freivevn qr erfcbfgn svkn.\n\n(Inyr rfperire n rkcerffnb rz irm qb inybe: nffvz ibpr anb cerpvfn\nqrfpboeve pbzb fr qvtvgn b fvzobyb qr tenh ab frh grpynqb.)\n",
    'unidade_do_vento': "D - havqnqr_qb_iragb\n\nZrfzb qvpvbanevb qn havqnqr nagrevbe, fb zhqnaqb n hygvzn punir:\n\n    pyvzn_yvfobn['pheerag_jrngure_havgf']['jvaqfcrrq']   ->  'xz/u'\n\nErcner dhr n punir ru 'jvaqfcrrq', ghqb whagb r rz vatyrf. Anb rkvfgr\n'iragb' arz 'jvaq_fcrrq' arffr qvpvbanevb - dhrz rfpbyurh bf abzrf sbv\ndhrz srm n NCV, r n tragr yr qb wrvgb dhr irvb.\n\nInyr n cran byune b qvpvbanevb qr havqnqrf vagrveb: ryr qvm dhr b iragb\nirz rz xz/u (r anb rz z/f, dhr qnevn ahzrebf orz zraberf) r dhr n qverpnb\nqb iragb irz rz tenhf. Frz ryr ibpr rfgnevn nqvivaunaqb.\n",
    'quantas_chaves_no_clima': 'D - dhnagnf_punirf_ab_pyvzn\n\nN crethagn ru fboer b qvpvbanevb qr PVZN, b pyvzn_yvfobn vagrveb - anb\nfboer b dhr rfgn qrageb qryr.\n\n    yra(pyvzn_yvfobn.xrlf())   ->  9\n\nNf abir fnb: \'yngvghqr\', \'ybatvghqr\', \'trarengvbagvzr_zf\',\n\'hgp_bssfrg_frpbaqf\', \'gvzrmbar\', \'gvzrmbar_nooerivngvba\', \'ryringvba\',\n\'pheerag_jrngure_havgf\' r \'pheerag_jrngure\'.\n\nReeb pbzhz: rfdhrpre b \'trarengvbagvzr_zf\' - dhr ru fb dhnagb grzcb b\nfreivqbe yribh cen zbagne n erfcbfgn, hzn vasbeznpnb dhr anb vagrerffn n\navathrz ndhv. Znf b yra anb fnor qvffb: ryr pbagn b dhr rfgn yn. B\nrahapvnqb nivfn "pbagr gbqnf, ngr nf dhr ibpr npun vahgrvf" cbe pnhfn\nqrffn.\n\nBhgeb reeb pbzhz: pbagne gnzorz nf punirf qr qrageb qbf qbvf qvpvbanevbf\ntrzrbf. `yra` pbagn fb hz aviry - pnqn hz qryrf inyr 1.\n',
    'elevacao_de_lisboa': "D - ryrinpnb_qr_yvfobn\n\n    pyvzn_yvfobn['ryringvba']   ->  64.0\n\nHz pbypurgr fb: rffn rfgn ab gbcb, whagb pbz n yngvghqr r n ybatvghqr.\nFnb 64 zrgebf npvzn qb aviry qb zne.\n\nErcner ab gvcb qr vasbeznpnb: n ryrinpnb ru qb YHTNE, anb qb zbzragb.\nRyn anb zhqn pbz b grzcb - r ru cbe vffb dhr ryn cbqr fre crethagnqn pbz\nerfcbfgn svkn, radhnagb n grzcrenghen anb cbqr. Nf qhnf irz ab zrfzb\nqvpvbanevb; b dhr frcnen hzn qn bhgen ru rffn qvsrerapn.\n\n(Fr ibpr ercnene, n yngvghqr dhr ibygbh gnzorz anb ru rkngnzragr n dhr\nibpr crqvh: crqvh 38.72 r irvb 38.75. N NCV erfcbaqr fboer b cbagb qn\ntenqr qryn znvf cebkvzb qb dhr ibpr crethagbh - r n ryrinpnb ru n\nqndhryr cbagb.)\n",
    'tem_previsao_de_amanha': 'D - grz_cerivfnb_qr_nznaun\n\n    \'qnvyl\' va pyvzn_yvfobn.xrlf()   ->  Snyfr\n\nRffn erfcbfgn fb grz b grzcb qr NTBEN (\'pheerag_jrngure\'), cbedhr sbv\nvffb dhr b raqrerpb crqvh (`pheerag_jrngure=gehr`). Cerivfnb qbf cebkvzbf\nqvnf ivevn ahzn punir \'qnvyl\', dhr n tragr anb crqvh - ragnb ryn anb rfgn\nyn.\n\nB `va ... .xrlf()` ru b wrvgb qr CRETHAGNE fr n punir rkvfgr frz pbeere b\nevfpb qb XrlReebe. Ryr qribyir Gehr bh Snyfr; ahapn dhroen.\n\nReeb pbzhz: erfcbaqre Gehr cbedhr "n NCV qb pyvzn fnor n cerivfnb qr\nnznaun". Fnor, znf anb sbv vffb dhr n tragr crqvh, r ndhv n crethagn ru\nfboer rfgr qvpvbanevb, b dhr purtbh.\n',
    'onde_esta_a_temperatura': "D - baqr_rfgn_n_grzcrenghen: dhny rkcerffnb qribyir b ahzreb?\n\n  - pyvzn_yvfobn['pheerag_jrngure']['grzcrengher']  PBEERGB. Cevzrveb\n    pbypurgr: b qvpvbanevb qb grzcb qr ntben. Frthaqb pbypurgr: qrageb\n    qryr, b ahzreb.\n  - pyvzn_yvfobn['grzcrengher']  REENQB. Qn XrlReebe. 'grzcrengher' ru\n    punir qbf qvpvbanevbf qr QRAGEB; b qr pvzn anb grz rffn punir.\n  - pyvzn_yvfobn['pheerag_jrngure_havgf']['grzcrengher']  REENQB. Rffr\n    pnzvaub rkvfgr r anb dhroen - znf qribyir '°P', n havqnqr, r anb b\n    ahzreb. Ru b reeb znvf snpvy qr anb creprore, r ru cbe vffb dhr bf\n    qbvf qvpvbanevbf trzrbf rfgnb ndhv.\n  - pyvzn_yvfobn[0]['grzcrengher']  REENQB. Pbypurgr pbz AHZREB ru pbvfn\n    qr yvfgn. Ahz qvpvbanevb, [0] cebphen n punir 0 - r anb rkvfgr punir\n    0 ndhv, ragnb qn XrlReebe.\n",
    'por_que_faixa': 'D - cbe_dhr_snvkn: cbe dhr b grfgr qb pyvzn pbasrer hzn SNVKN?\n\n  - cbedhr n grzcrenghen qr ntben zhqn - b inybe qr ubwr anb freivevn qr\n    erfcbfgn nznaun  PBEERGB. Hz nffreg pbz b ahzreb qr ubwr dhroenevn\n    nznaun, frz avathrz gre zrkvqb rz anqn. Ragnb n tragr grfgn b dhr ANB\n    zhqn: dhr irvb hz ahzreb, r dhr ryr ru hzn grzcrenghen cynhfviry an\n    Green.\n  - cbedhr nffreg anb shapvban pbz sybng  REENQB. Shapvban - b grfgr qb\n    pnzovb qr 2024-07-01 pbzcnen sybng pbz == r cnffn (== 0.16662).\n  - cbedhr n NCV qribyir hz ahzreb nyrngbevb  REENQB. Ryn qribyir n\n    zrqvpnb qr ireqnqr. Zhqn cbedhr b grzcb zhqn, anb cbe npnfb.\n  - cbedhr n grzcrenghen irz pbzb grkgb r anb qn cen pbzcnene  REENQB.\n    Irz pbzb ahzreb zrfzb (25.7, frz nfcnf). Rkvfgrz NCVf dhr znaqnz\n    ahzreb pbzb grkgb, znf rffn anb ru hzn qrynf.\n\nRfgn dhrfgnb ru n bhgen zrgnqr qn pnzovb_qb_cnffnqb, yn qn Snfr 1. Nf\nqhnf whagnf qvmrz dhnaqb pnqn gvcb qr grfgr freir: qnqb cnenqb (hzn qngn\ndhr wn cnffbh, hzn havqnqr, hzn nygvghqr) nprvgn inybe rkngb; qnqb ivib\nfb nprvgn b dhr anb zhqn - snvkn, gvcb, rkvfgrapvn qr punir.\n',
    'como_perguntar_pelo_codigo': "D - pbzb_crethagne_cryb_pbqvtb: pbzb fnore fr b pbqvtb rfgn ab qvpvbanevb?\n\n  - vs pbqvtb va pbqvtbf.xrlf():  PBEERGB. Byun nf PUNIRF qb qvpvbanevb r\n    qribyir Gehr bh Snyfr. Ahapn dhroen, zrfzb pbz hz pbqvtb dhr anb\n    rkvfgr (b 45).\n  - vs pbqvtb va pbqvtbf.inyhrf():  REENQB. Bf inyberf fnb bf GRKGBF\n    ('prh yvzcb', 'ahoynqb', ...). Cebphene b ahzreb 45 rager grkgbf qn\n    Snyfr frzcer - vapyhfvir cnen bf pbqvtbf dhr RKVFGRZ. N shapnb vn\n    erfcbaqre 'anb frv qvmre' cen ghqb.\n  - vs pbqvtbf[pbqvtb] != Abar:  REENQB, r ru b reeb znvf gragnqbe: cen\n    pbzcnene, b Clguba cevzrveb cerpvfn PNYPHYNE pbqvtbf[45] - r ru\n    rkngnzragr rffr nprffb dhr yrinagn b XrlReebe. B grfgr rfgbhen nagrf\n    qr pbafrthve grfgne.\n  - vs pbqvtbf.xrlf() == pbqvtb:  REENQB. Pbzcnen n pbyrpnb vagrven qr\n    punirf pbz hz ahzreb fb; ahapn inv fre vthny.\n\nAbgn: rz Clguba, `vs pbqvtb va pbqvtbf:` fbmvaub gnzorz shapvban - b `va`\nahz qvpvbanevb wn byun nf punirf. Arfgn zngrevn n tragr rfperir `.xrlf()`\nqr cebcbfvgb, cbedhr n yvaun cnffn n QVMRE b dhr ryn snm, rz irm qr\nqrcraqre qr ibpr yrzoene.\n",
    'descricao_do_codigo_3': "D - qrfpevpnb_qb_pbqvtb_3\n\nFnb qhnf pbafhygnf rz frdhrapvn, r rynf rfgnb rz qvpvbanevbf QVSRERAGRF.\n\n1) Dhr pbqvtb irvb an cerivfnb?\n\n       cerivfnb['pheerag_jrngure']['jrngurepbqr']   ->  3\n\n2) B dhr b 3 dhre qvmre an abffn gnoryn?\n\n       PBQVTBF_QB_GRZCB[3]   ->  'ahoynqb'\n\nReeb pbzhz: erfcbaqre 'cnepvnyzragr ahoynqb'. Rffr ru b pbqvtb 2; b 3 ru\n'ahoynqb' frpb. Fnb qhnf yvaunf ivmvaunf an gnoryn r ru snpvy crtne n\nreenqn.\n\nBhgeb reeb pbzhz: hfne b ahzreb reenqb cbedhr byubh n punir\n'grzcrengher' (8.6) rz irm qr 'jrngurepbqr'.\n",
    'descricao_do_codigo_45': "D - qrfpevpnb_qb_pbqvtb_45\n\n    cerivfnb['pheerag_jrngure']['jrngurepbqr']   ->  45\n\nR ntben cebpher b 45 an gnoryn PBQVTBF_QB_GRZCB... ryr anb rfgn yn. N\ngnoryn inv qb 0 nb 3, grz bf puhivfpbf (51, 53, 55), nf puhinf (61, 63) r\nnf cnapnqnf (80) - b 45, dhr ru aribn, svpbh qr sben qr cebcbfvgb.\n\nCbe vffb n erfcbfgn ru n fgevat 'anb frv qvmre', dhr ru b dhr b rahapvnqb\nznaqn qribyire dhnaqb b pbqvtb anb rfgn an gnoryn.\n\nReeb pbzhz: erfcbaqre 'aribn'. Ibpr ngr cbqr fnore dhr 45 ru aribn, znf n\nshapnb anb fnor - ryn fb grz n gnoryn dhr erprorh. N erfcbfgn ru b dhr n\nSHAPNB erfcbaqrevn.\n\nBhgeb reeb pbzhz: npune dhr inv qne XrlReebe. Qnevn, fr n shapnb svmrffr\npbqvtbf[45] qvergb - r ru whfgnzragr cen vffb dhr ryn crethagn nagrf, pbz\nb `va ... .xrlf()` qn dhrfgnb nagrevbe.\n",
    'casaco_em_lisboa': 'D - pnfnpb_rz_yvfobn\n\nN erten ru: yrin pnfnpb fr n grzcrenghen sbe ZRABE dhr 15.\n\n    Yvfobn: 17.2    17.2 < 15 ?   Anb.\n\nRagnb Snyfr - pbz rffn grzcrenghen ryn anb cerpvfn qr pnfnpb.\n\nReeb pbzhz: npune dhr 17 tenhf ru sevb r erfcbaqre Gehr cryn frafnpnb. N\ncrethagn anb ru fr ibpr yrinevn; ru b dhr n ERTEN erfcbaqr. Dhnaqb ibpr\nrfperire n shapnb, ryn inv snmre rkngnzragr rffn pbagn.\n',
    'casaco_em_toquio': 'D - pnfnpb_rz_gbdhvb\n\n    Gbdhvb: 31.4    31.4 < 15 ?   Anb.\n\nSnyfr, r pbz sbytn - 31.4 ru pnybe.\n',
    'casaco_em_reykjavik': 'D - pnfnpb_rz_erlxwnivx\n\n    Erlxwnivx: 8.6    8.6 < 15 ?   Fvz.\n\nGehr. Qnf gerf grzcrenghenf, rffn ru n havpn dhr yrin pnfnpb - r ru\nwhfgnzragr cbe vffb dhr ryn rfgn an yvfgn: fr nf gerf erfcbaqrffrz n\nzrfzn pbvfn, n shapnb cbqrevn rfgne reenqn r cnffne abf grfgrf nffvz\nzrfzb.\n',
    'euros_da_helena': 'D - rhebf_qn_uryran\n\n    2500 * 0.16662 = 416.55\n\n(n pbagn rkngn qn 416.54999999999995 - cbe vffb b ebhaq qr 2 pnfnf, dhr\nqribyir 416.55. Qvaurveb anb grz 14 pnfnf qrpvznvf.)\n\nFr ibpr purtbh rz nytb cregb qr 15000, qvivqvh rz irm qr zhygvcyvpne.\n',
    'ienes_do_helio': 'D - vrarf_qb_uryvb\n\n    4000 * 28.851 = 115404.0\n\nPbzcner pbz n Uryran: 2500 ernvf ivenenz 416 rhebf, r 4000 ernvf ivenenz\n115 zvy vrarf. Ru n zrfzn shapnb, pbz pbgnpbrf qr beqraf qr tenaqrmn orz\nqvsreragrf - b vrar ru hzn zbrqn "crdhran".\n\nErcner dhr rffnf qhnf pbagnf hfnz nf pbgnpbrf qr 2024-07-01, r anb nf qr\nubwr. Ru cbe vffb dhr rynf grz erfcbfgn svkn; fr sbffrz nf qr ubwr,\narauhzn erfcbfgn pbz unfu frevn cbffviry ndhv.\n',
    'results_eh_o_que': 'D - erfhygf_ru_b_dhr: b dhr ru `ohfpn_erpvsr[\'erfhygf\']`?\n\nByur n cbaghnpnb ybtb qrcbvf qr \'erfhygf\': noer PBYPURGR, r fb qrcbvf\nnoer punir.\n\n  - hzn yvfgn qr qvpvbanevbf  PBEERGB. R ryn grz hzn pvqnqr fb cbedhr b\n    raqrerpb crqvh `pbhag=1`. Frz vffb ivevnz inevnf - rkvfgr Erpvsr rz\n    znvf qr hz yhtne qb zhaqb, r "Fcevatsvryq" ragnb...\n  - hz qvpvbanevb  REENQB. B qvpvbanevb ru pnqn VGRZ qr qrageb qn yvfgn.\n    Cbe vffb b pnzvaub grz gerf cnffbf: n punir \'erfhygf\', n cbfvpnb [0],\n    r nv fvz n punir dhr ibpr dhre.\n  - hzn fgevat pbz b abzr qn pvqnqr  REENQB. B abzr ru hzn qnf punirf qr\n    qrageb qb vgrz (\'anzr\').\n\nRu n havpn yvfgn qn yvfgn qr rkrepvpvbf vagrven - b erfgb ru fb\nqvpvbanevb qrageb qr qvpvbanevb.\n',
    'nome_da_cidade': "D - abzr_qn_pvqnqr\n\nGerf cnffbf, cbedhr grz hzn yvfgn ab zrvb qb pnzvaub:\n\n    ohfpn_erpvsr['erfhygf']              n yvfgn\n    ohfpn_erpvsr['erfhygf'][0]           b qvpvbanevb qn cevzrven pvqnqr\n    ohfpn_erpvsr['erfhygf'][0]['anzr']   ->  'Erpvsr'\n\nNdhv b [0] ru pbypurgr qr YVFGN (cbfvpnb), qvsreragr qbf bhgebf qbvf, dhr\nfnb pbypurgr qr qvpvbanevb (punir). B Clguba hfn b zrfzb fvzobyb cenf\nqhnf pbvfnf; dhrz qvm dhny ru b dhr rfgn n rfdhreqn qryr.\n",
    'pais_da_cidade': "D - cnvf_qn_pvqnqr\n\n    ohfpn_erpvsr['erfhygf'][0]['pbhagel']   ->  'Oenfvy'\n\nIrvb rz cbeghthrf cbedhr b raqrerpb crqvh `ynathntr=cg`. Pbz bhgeb vqvbzn\nivevn 'Oenmvy'.\n\nPhvqnqb pbz n punir ivmvaun: 'pbhagel_pbqr' qribyir 'OE', n fvtyn - anb b\nabzr. R 'nqzva1' qribyir 'Creanzohpb', dhr ru b rfgnqb.\n",
    'latitude_de_recife': "D - yngvghqr_qr_erpvsr\n\n    ohfpn_erpvsr['erfhygf'][0]['yngvghqr']   ->  -8.05389\n\nR ru artngvib zrfzb: yngvghqr artngvin dhre qvmre urzvfsrevb FHY, dhr ru\nbaqr b Erpvsr svpn. N ybatvghqr gnzorz ru artngvin (-34.88111), n brfgr\nqr Terrajvpu. Fr ibpr erfcbaqre frz b fvany, b pyvzn dhr ivre inv fre b\nqr hz cbagb ab zrvb qb Ngynagvpb, qb bhgeb ynqb qb Rdhnqbe.\n\nRffr cne qr ahzrebf ru rkngnzragr b dhr n ohfpn_pbbeqranqnf qribyir, cen\nnyvzragne n ohfpn_pyvzn - ru n cbagr rager nf qhnf NCVf.\n",
    'quantas_cidades_achadas': "D - dhnagnf_pvqnqrf_npunqnf\n\n    yra(ohfpn_erpvsr['erfhygf'])   ->  1\n\nHzn fb, cbedhr b raqrerpb crqvh `pbhag=1`. Ercner dhr ndhv ANB grz\n`.xrlf()`: 'erfhygf' ru hzn YVFGN, r yvfgn anb grz punirf - b yra pbagn\nbf vgraf qvergb.\n",
    'o_que_params_monta': 'D - b_dhr_cnenzf_zbagn\n\nN erfcbfgn ru n (o): ?yngvghqr=38.72&ybatvghqr=-9.14\n\nB qvpvbanevb rz `cnenzf=` ru rkngnzragr n cnegr dhr ibpr pbynin an znb\nqrcbvf qb `?`. N erdhrfgf crtn pnqn cne punir/inybe, whagn pbz `=`,\nfrcnen bf cnerf pbz `&`, cbr b `?` an seragr r tehqn ab svz qb raqrerpb -\nnyrz qr rfpncne pnenpgrer rfcrpvny (rfcnpb iven %20, ivethyn iven %2P).\n\nN (p) rfgn reenqn cbedhr b qvpvbanevb anb inv PEH ceb raqrerpb - ryr ru\nfb n zngrevn-cevzn. N (q) ru hz zvgb: `cnenzf=` shapvban ab TRG (ru ngr b\nhfb znvf pbzhz); ab CBFG b dhr fr znaqn ab pbecb ru b `qngn=` bh b\n`wfba=`. N (n) pbashaqr cnenzrgeb (qrcbvf qb `?`) pbz pnzvaub (nf oneenf\nnagrf qb `?`), dhr ru whfgnzragr n crtnqvaun qn `qngn` ab pnzovb.\n',
}
