"""Explicacoes das questoes teoricas - brasileirao1.

O conteudo esta em ROT13 de proposito: visivel no arquivo, mas
ilegivel a olho nu, para nao entregar a resposta a quem so rola o
arquivo. A funcao explicar() do exercicio decodifica e imprime.

NAO edite este arquivo a mao - ele eh gerado por
NAO_MANDAR_montar_explicacao_brasileirao1.py.
"""

EXPLICACOES = {
    'nome_comum_do_primeiro_colocado': "D - abzr_pbzhz_qb_cevzrveb_pbybpnqb: b abzr-pbzhz qb cevzrveb pbybpnqb.\n\nErfbyiraqb cnffb n cnffb, qr qrageb cen sben:\n\n1) cevzrveb qrfpboevzbf n vq qb cevzrveb pbybpnqb:\n\n       qnqbf2018['snfrf']['2700']['pynffvsvpnpnb']['tehcb']['havpb'][0]\n\n   B cevzrveb pbybpnqb ru b CEVZRVEB ryrzragb qn yvfgn qr pynffvsvpnpnb,\n   ragnb b [0] ab svz. B erfhygnqb qrffn rkcerffnb ru '17' (n vq qb\n   Cnyzrvenf).\n\n2) rffn vq iven n PUNIR qr ohfpn ab qvpvbanevb qr rdhvcrf:\n\n       qnqbf2018['rdhvcrf']['17']['abzr-pbzhz']  ->  'Cnyzrvenf'\n\nWhagnaqb ghqb ahzn rkcerffnb fb:\n\n       qnqbf2018['rdhvcrf'][qnqbf2018['snfrf']['2700']['pynffvsvpnpnb']['tehcb']['havpb'][0]]['abzr-pbzhz']\n\nB pbypurgr qr qrageb ebqn cevzrveb (iven '17'), r b pbypurgr qr sben\nhfn '17' pbzb punir qb qvpvbanevb qr rdhvcrf.\n\nReebf cerivfvirvf:\n  - Rfdhrpre b [0]: b pbypurgr qr qrageb qribyirevn n YVFGN vagrven qr\n    pynffvsvpnpnb, r hfne hzn yvfgn pbzb punir qr qvpvbanevb qn GlcrReebe.\n  - Gebpne 'abzr-pbzhz' cbe 'abzr': b pnzcb 'abzr' rkvfgr, znf qribyir b\n    abzr PBZCYRGB (rk: 'Fbpvrqnqr Rfcbegvin Cnyzrvenf'), anb b pbzhz.\n  - Rfdhrpre ['snfrf']['2700'] ab zrvb qb pnzvaub: b qvpvbanevb cevapvcny\n    anb grz n punir 'pynffvsvpnpnb' qvergb - qn XrlReebe.\n",
    'o_que_e_dados_equipes': "D - b_dhr_r_qnqbf_rdhvcrf: b dhr ru `qnqbf['rdhvcrf']`?\n\nB qvpvbanevb cevapvcny `qnqbf` grz n punir 'rdhvcrf'. B INYBE qryn ru\nBHGEB qvpvbanevb (qvpvbanevb qrageb qr qvpvbanevb):\n\n    qnqbf['rdhvcrf']['6']  ->  {'vq': '6',\n                                'abzr': 'Fcbeg Pyho Pbevaguvnaf Cnhyvfgn',\n                                'abzr-pbzhz': 'Pbevaguvnaf',\n                                'fvtyn': 'PBE', ...}\n\nBh frwn: n PUNIR ru n vq qb gvzr (hzn fgevat), r b INYBE ru n SVPUN qb\ngvzr. Cbe vffb n erfcbfgn pregn: hz qvpvbanevb dhr, cnen pnqn vq qr gvzr,\nthneqn n svpun qryr.\n\nNf bhgenf nygreangvinf:\n  - hzn yvfgn pbz bf abzrf qbf gvzrf  REENQB. Yvfgn anb fr vaqrkn cbe\n    punir - fr sbffr yvfgn, qnqbf['rdhvcrf']['6'] anb snevn fragvqb.\n  - hzn yvfgn pbz nf vqf qbf gvzrf  REENQB. Nf vqf fnb nf PUNIRF qrffr\n    qvpvbanevb, anb b pbagrhqb thneqnqb.\n  - qvpvbanevb abzr -> vq  REENQB. Bf abzrf svpnz QRAGEB qnf svpunf (rz\n    'abzr-pbzhz'), anb fnb punirf; r frevn b pnzvaub vairefb qb dhr grzbf.\n",
    'por_que_equipes_0_falha': 'D - cbe_dhr_rdhvcrf_0_snyun: b dhr npbagrpr pbz `qnqbf[\'rdhvcrf\'][0]`?\n\nQvpvbanevb fr vaqrkn cbe PUNIR, anb cbe cbfvpnb. Nf punirf qr\nqnqbf[\'rdhvcrf\'] fnb nf vqf qbf gvzrf: \'1\', \'3\', \'4\', \'6\', \'9\', ...\n\n`qnqbf[\'rdhvcrf\'][0]` crethagn cryn punir 0 (b vagrveb mreb). Arauhz gvzr\ngrz n vq \'0\' - ragnb b clguba qn XrlReebe.\n\nN erfcbfgn pregn: qn XrlReebe - r vffb ANB ru oht frh: ru n erten qb wbtb\nqbf qvpvbanevbf.\n\nNf bhgenf nygreangvinf:\n  - qribyir b cevzrveb gvzr  REENQB. Vffb inyrevn cen hzn YVFGN (yvfgn fr\n    vaqrkn cbe cbfvpnb). Qvpvbanevb anb grz cbfvpnb. Fr dhvfre b "cevzrveb"\n    ab fragvqb qr pynffvsvpnpnb, b pnzvaub ru n yvfgn qr pynffvsvpnpnb\n    ([...][\'tehcb\'][\'havpb\'][0]).\n  - qribyir b Pbevaguvnaf  REENQB. B Pbevaguvnaf ru n punir \'6\':\n    qnqbf[\'rdhvcrf\'][\'6\'].\n  - qribyir hzn yvfgn pbz gbqbf bf gvzrf  REENQB. qnqbf[\'rdhvcrf\'] (frz\n    pbypurgr) ru dhr ru b qvpvbanevb vagrveb; pbz [0] ibpr rfgn gragnaqb\n    hzn punir dhr anb rkvfgr.\n',
    'caminho_ate_o_campeao': "D - pnzvaub_ngr_b_pnzcrnb: n nygreangvin dhr qribyir b ABZR-PBZHZ qb pnzcrnb.\n\nPnqn nygreangvin grz QHNF yvaunf. N cevzrven thneqn ahzn inevniry\n(cevzrven_vq) b erfhygnqb qr hz crqnpb qn ohfpn; n frthaqn hfn rffn\ninevniry.\n\nB pnzcrnb ru b CEVZRVEB qn yvfgn qr pynffvsvpnpnb. N nygreangvin pregn:\n\n    cevzrven_vq = qnqbf['snfrf']['2700']['pynffvsvpnpnb']['tehcb']['havpb'][0]\n    qnqbf['rdhvcrf'][cevzrven_vq]['abzr-pbzhz']\n\nCnffb n cnffb:\n  1) n cevzrven yvaun npun n vq qb pnzcrnb ('17') r thneqn rz cevzrven_vq;\n  2) n frthaqn yvaun hfn cevzrven_vq pbzb PUNIR qb qvpvbanevb qr rdhvcrf\n     r crtn b pnzcb 'abzr-pbzhz' (-> 'Cnyzrvenf').\n\nNygreangvin cbe nygreangvin (ercnenaqb an CEVZRVEN r an FRTHAQN yvaun):\n  - cevzrven yvaun qnqbf['rdhvcrf'][0]  REENQB. Vaqrkn b qvpg qr rdhvcrf\n    cryn cbfvpnb 0 - anb rkvfgr n punir 0, qn XrlReebe an cevzrven yvaun.\n  - cevzrven yvaun frz b [0] ab svz  REENQB. Qribyirevn n YVFGN vagrven\n    qr pynffvsvpnpnb; n frthaqn yvaun hfnevn hzn yvfgn pbzb punir qr\n    qvpvbanevb - GlcrReebe.\n  - cevzrven yvaun pbz [1] ab yhtne qb [0]  REENQB. [1] crtn b IVPR (b\n    Synzratb), anb b pnzcrnb.\n  - frthaqn yvaun pbz 'abzr' ab yhtne qr 'abzr-pbzhz'  REENQB. 'abzr'\n    qribyir b abzr PBZCYRGB ('Fbpvrqnqr Rfcbegvin Cnyzrvenf'), anb b\n    abzr pbzhz.\n  - cevzrven yvaun ...['havpb']['0']  REENQB. '0' (fgevat) pbzb vaqvpr qr\n    YVFGN: yvfgn fr vaqrkn cbe AHZREB - qn GlcrReebe.\n  - cevzrven yvaun qnqbf['pynffvsvpnpnb']['tehcb']['havpb'][0]  REENQB.\n    Snygn b ['snfrf']['2700']: b qvpvbanevb cevapvcny anb grz n punir\n    'pynffvsvpnpnb' qvergb - qn XrlReebe.\n  - cevzrven yvaun cevzrven_vq = '17'  REENQB (znf fhgvy!). N frthaqn\n    yvaun shapvban FBMVAUN (b Cnyzrvenf sbv pnzcrnb qr ireqnqr), znf n\n    vq rfgn PUHZONQN: anb yr n pynffvsvpnpnb. Fr bf qnqbf zhqnerz,\n    pbagvahn qribyiraqb b Cnyzrvenf.\n  - cevzrven yvaun pbz [2] ab yhtne qb [0]  REENQB. [2] crtn b GREPRVEB\n    (b Vagreanpvbany).\n  - frthaqn yvaun pbz 'fvtyn' ab yhtne qr 'abzr-pbzhz'  REENQB. 'fvtyn'\n    qribyir 'CNY', anb b abzr pbzhz.\n",
}
